# compose.yaml
services:
  app:
    build:
      context: .
    entrypoint: php artisan octane:frankenphp --workers=1 --max-requests=1 --port=80 --host=0.0.0.0
    ports:
      - "80:80"
    volumes:
      - .:/app
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: ${APP_KEY}
      DB_CONNECTION: pgsql
      DB_HOST: ${DB_HOST}       # tu Postgres en Coolify
      DB_PORT: 5432
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_BUCKET: ${AWS_BUCKET}
      AWS_ENDPOINT: ${AWS_ENDPOINT}
      AWS_USE_PATH_STYLE_ENDPOINT: "true"
      OCTANE_HTTPS: "false"
